run:
linters-settings:
  golint:
    min-confidence: 0.9

skip-dirs:
    - pkg/cluster-registry

linters:
  disable-all: true
  enable:
    - staticcheck
    - ineffassign
    - golint
    - goimports
    - errcheck
issues:
  exclude-rules:
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
