language: go

go:
  - "1.12.x"

env:
- GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/lawrencewoodman/roveralls
  - go get honnef.co/go/tools/cmd/staticcheck

script:
  - make build.docker
  - make test
  - roveralls
  - goveralls -v -coverprofile=roveralls.coverprofile -service=travis-ci
