language: go
dist: xenial

go:
  - "1.13.x"

env:
- GOLANGCI_RELEASE="v1.21.0"

before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls
  - GO111MODULE=off go get github.com/lawrencewoodman/roveralls
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_RELEASE}


script:
  - make build.docker
  - make test
  - make lint
  - roveralls
  - goveralls -v -coverprofile=roveralls.coverprofile -service=travis-ci
